### ISSUE TITLE
Could not find app file while mix compile

### ISSUE THREAD

**Issue by 0xGGGGG** [elixir-circuits/circuits_sim#17]
Hey there! Great initiative, it's probably going to clear out all the mocks for sensors I'm using.

I gave an initial try but I'm stuck at `mix compile` stage, with this error:

```
Unchecked dependencies for environment dev:
* circuts_sim (https://github.com/elixir-circuits/circuits_i2c.git)
  could not find an app file at "_build/dev/lib/circuts_sim/ebin/circuts_sim.app". Another app file was found in the same directory "_build/dev/lib/circuts_sim/ebin/circuits_i2c.app", try changing the dependency name to :circuits_i2c
** (Mix) Can't continue due to errors on dependencies
```

I tried to follow the README, but I'm not sure if I'm doing sth wrong. So, here is my simplified mix.exs file:

```ex
defmodule MyProject.MixProject do
  use Mix.Project

  # ...

  defp deps do
    [
      # ...

      # I2C sensors
      {:circuits_i2c, "~> 2.0", override: true},
      {:circuits_spi, "~> 2.0.0-pre.0"},
      {:circuits_gpio, "~> 2.0.0-pre.0"},
      {:circuts_sim, github: "elixir-circuits/circuits_i2c", targets: :host},
      {:bmp280, "~> 0.2"},
      {:bh1750, "~> 0.2.0"},
      {:sgp40, "~> 0.1.5"}
    ]
  end
end
```

Backend config is defined for i2c in `host.exs` file:
(I don't think mix compile arrived at this stage though since it failed at gathering dependency apps)

```ex
config :circuits_i2c, default_backend: CircuitsSim.I2C.Backend
```

I also tried to clean up dependencies with `mix deps.clean --all` and `rm -rf _build`, but no luck.

Let me know if you need more info!

**Comment by fhunleth** [comment]
Could you update this line:

```
 {:circuts_sim, github: "elixir-circuits/circuits_i2c", targets: :host},
```

to:
 
```
 {:circuits_sim, github: "elixir-circuits/circuits_sim", targets: :host},
```

**Comment by 0xGGGGG** [comment]
> Could you update this line:

Oh shoot, yeah! My bad, thanks for being my remote debugger, that fixed it. 💜
