### ISSUE TITLE
Release circuits_sim

### ISSUE THREAD

**Issue by a-maze-d** [elixir-circuits/circuits_sim#20]
Now that all circuits libraries are on >2.0, it's maybe time to release `circuits_sim` as well

**Comment by fhunleth** [comment]
Hi @a-maze-d - you're totally right. I had been wanting to revisit one of the abstractions, but lacking time. It's "good enough". I'll try to get a release out this week.

**Comment by fhunleth** [comment]
@a-maze-d I made a v0.1.0 release and pushed to hex. My time is so limited right now that I just did the best that I can. If something doesn't seem right to you, could you help with a fix? I'm also open to chatting if you'd like to help maintain this project.

Thanks again for the push to get this out there officially.

**Comment by a-maze-d** [comment]
Great. Thanks a lot.

I used it in my library (fledex) and it brings tremendous value. And there are always things that can be improved. 

And I know the feeling of time being in shortage. Thus don't feel bad. Your library is great. .I'm already feeling I'm letting my son down for whom I write my library and its only slow progress.Therefore not offering any help right now
